name: Run Django Tests on PR

on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:

      - run: |
          sudo apt-get update
          sudo apt-get install -y \
          libffi-dev libldap2-dev libpq-dev libsasl2-dev \
          python3-dev postgresql-contrib


      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set Up uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        working-directory: ${{ github.workspace }}
        run: |
          uv sync 

      - name: Run Tests
        working-directory: ${{ github.workspace }}/teamvault
        run: |
          python manage.py test
