name: Run Django Tests on PR

on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      TEAMVAULT_CONFIG_FILE: ${{ github.workspace }}/teamvault.cfg
    steps:

      - run: |
          sudo apt-get update
          sudo apt-get install -y \
          libffi-dev libldap2-dev libpq-dev libsasl2-dev \
          python3-dev postgresql-contrib


      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set Up uv
        uses: astral-sh/setup-uv@v5

      # Install TeamVault from source because the latest PyPI release (0.9.2 as of 2025-07-28) isn’t yet Python 3.12-compatible
      - name: Install dependencies
        working-directory: ${{ github.workspace }}
        run: |
          uv sync && uv pip install -e .

      - name: Activate venv for later steps
        shell: bash
        run: |
          echo "${{ github.workspace }}/.venv/bin" >> "$GITHUB_PATH"

      - name: Set Up TeamVault Config File
        working-directory: ${{ github.workspace }}
        run: |
          teamvault setup

      - name: Run Tests
        working-directory: ${{ github.workspace }}/teamvault
        run: |
          python manage.py test
