name: Run Django Tests on PR

on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set Up uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: |
          uv sync 

      - name: Run Tests
        run: |
          python manage.py test
